server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    password: vivek
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: UserServices



